networks:
  my_custom_network:
    name: my_custom_network
    driver: bridge
    external: true

services:
  gateway-api:
    build: .
    ports:
      - "6060:8080"
    networks:
      - my_custom_network